GET http://localhost:3001/users

###

GET http://localhost:3001/users/63d0080a2ab5c2e712ed6947

###

GET http://localhost:3001/users/username/MartinPezet

###

# POST http://localhost:3001/users
Content-Type: application/json

{
  "userName": "MartinPezet",
  "email": "mpezet@ntlworld.com",
  "permissionLevel": 1
}

