name: Build

on:
  workflow_dispatch: # Manually be able to run it
  
jobs:
  Docker:
    runs-on: ubuntu-latest # Linux is the cheapest
    steps:
      - uses: actions/checkout@v3 # Able to use git functions in container
      - uses: actions/setup-node@v3 # Adds node to docker allowing npm
        with:
          node-version: 14
      - name: Setup bot user # Increases version on every commit to master/main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
        
      - name: Dependencies
        working-directory: ./client
        run: npm ci # This is npm clean-install and will install all in package.json
        
      - name: Create new branch
        working-directory: ./client
        run: git checkout -b versionUpgrade
        
      - name: Build
        working-directory: ./client
        run: npm run build
        
      - name: Save version # Allows to save the version of node modules
        working-directory: ./client
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        
      - name: Increase version
        working-directory: ./client
        run: npm version patch
        
      - name: Commit Version Change
        working-directory: ./client
        run: git commit ./package.json ./package-lock.json -m "Automated Version Update"
                
      - name: Push new version
        run: git push --set-upstream origin versionUpgrade
        
      - name: Create Pull Request
        working-directory: ./client
        run: git version
        
        # The previous section was to build the react app, apply versions and push back to github
        
        # The next few steps are to create a docker image so a server can run this in a docker container and upgrade images easily
        
      - name: Login to DockerHub
        working-directory: ./client
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin # The secrets are a Github actions variable so public code doesn't include passwords and usernames
        
      - name: Build Docker Image
        working-directory: ./client
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website:${{steps.version.output.tag}} # Version is a previously set within the file (id: version)
        
      - name: Push to DockerHub
        working-directory: ./client
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website:${{steps.version.outputs.tag}}
        
