name: Test Build Landing Page

on:
  workflow_dispatch: # Manually be able to run it
    inputs:
        manual_branch:
          description: Set branch
          required: true
          type: string
          default: main
  
env:
  REACT_APP_SSO_API_BASE_URI: ${{ secrets.REACT_APP_SSO_API_BASE_URI }}

jobs:
  Docker:
    runs-on: ubuntu-latest # Linux is the cheapest
    environment: TEST
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3 # Able to use git functions in container
      - uses: actions/setup-node@v3 # Adds node to docker allowing npm
        with:
          node-version: 14
      - name: Setup bot user # Increases version on every commit to master/main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
        
      - name: Dependencies
        working-directory: ./client
        run: npm ci # This is npm clean-install and will install all in package.json
        
      - name: Build
        working-directory: ./client
        run: npm run build
        
      - name: Save version # Allows to save the version of node modules
        working-directory: ./client
        id: version
        run: echo "tag=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT
          
        
        # The previous section was to build the react app, apply versions and push back to github
        
        # The next few steps are to create a docker image so a server can run this in a docker container and upgrade images easily
        
      - name: Login to DockerHub
        working-directory: ./client
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin # The secrets are a Github actions variable so public code doesn't include passwords and usernames
        
      - name: Build Docker Image
        working-directory: ./client
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website-test:latest --tag ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website-test:${{steps.version.outputs.tag}} # Version is a previously set within the file (id: version)
        
      - name: Push Tagged Version to DockerHub
        working-directory: ./client
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website-test:${{steps.version.outputs.tag}}
        
      - name: Push Latest Version to DockerHub
        working-directory: ./client
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/portfolio-website-test:latest
        
